Fix Content-Lenght calculation of unicode string
encode/httpx pull request #1484
Opened 2021-02-24 09:10 UTC by j178

Fixes #1482

2021-02-28 12:00 UTC, florimondmanca requested changes
Looking very nice, just a few suggestions to make this tighter?

2021-02-28 15:21 UTC, j178 commented on httpx/_multipart.py
>              return len(headers) + len(self.file)
Yes. this is the simple and correct fix, I was trying to avoid an extra `to_bytes` call.

2021-03-12 10:37 UTC, tomchristie commented
Looks fiddly, just flagging up that I'd also like to be involved in any review on this. 😇

2021-03-24 13:41 UTC, tomchristie commented
Great, thanks for this, good work!

I'd like to see the change footprint reduced on it slightly. I don't think we really need to change `_types.py` at all, and I think we can reduce the number of changes in `_multipart.py`. I'll leave a couple of inline suggestions there.

2021-03-24 13:41 UTC, tomchristie commented on httpx/_multipart.py
> -            )
This is a nice tweak, yup.

2021-03-24 13:41 UTC, tomchristie commented on httpx/_multipart.py
> -
I'd suggest we don't change this.

2021-03-24 13:41 UTC, tomchristie commented on httpx/_multipart.py
> +
Or add this.

2021-03-24 13:42 UTC, tomchristie commented on httpx/_multipart.py
> -        if isinstance(self.file, (str, bytes)):
The low-footprint change here is presumably to keep this check the same, but use the following...

`return len(headers) + len(to_bytes(self.file))`

Right?

2021-03-24 13:43 UTC, tomchristie commented on httpx/_multipart.py
> -            yield to_bytes(self.file)
We shouldn't need to change this.

2021-03-25 15:30 UTC, closed without merging