use context.minimum_version in py3.7+ where available
encode/httpx pull request #1714
Opened 2021-06-25 08:45 UTC by graingert

ssl.OP_NO_TLSv1
ssl.OP_NO_TLSv1_1

are deprecated in py3.7+ and using these options prevents
downstream users of httpx.create_ssl_context using
minimum_versoin

The starting point for contributions should usually be [a discussion](https://github.com/encode/httpx/discussions)

Simple documentation typos may be raised as stand-alone pull requests, but otherwise
please ensure you've discussed your proposal prior to issuing a pull request.

This will help us direct work appropriately, and ensure that any suggested changes
have been okayed by the maintainers.

- [ ] Initially raised as discussion #...

2021-06-25 09:06 UTC, tomchristie commented
> are deprecated in py3.7+

Could you link to the relevant Python docs to help with reviewing this?

Given that we've enabled warnings-as-errors on our CI, wouldn't we expect to be raising errors here if we were using a deprecated Python API?

2021-06-25 09:09 UTC, graingert commented
https://docs.python.org/3.7/library/ssl.html#ssl.OP_NO_TLSv1

> Deprecated since version 3.7: The option is deprecated since OpenSSL 1.1.0, use the new SSLContext.minimum_version and SSLContext.maximum_version instead.

2021-06-25 09:24 UTC, tomchristie requested changes

2021-06-25 09:24 UTC, tomchristie commented on httpx/_compat.py
> +        )
Okay. I'd suggest we aim to keep the change footprint on pull requests as low as possible. Not reformatting the `context.options |= ...` style here would help with that.

```python
def set_minimum_tls_version_1_2(context: ssl.SSLContext) -> None:
     if (
        sys.version_info >= (3, 10) or
        sys.version_info >= (3, 7) and ssl.OPENSSL_VERSION_INFO >= (1, 1, 0, 7)
     ):
         # The 'minimum_version' attribute is available from Python 3.10 onwards,
         # Or Python 3.7 onwards if the ssl module is compiled with OpenSSL 1.1.0g
         # or newer.
         # https://docs.python.org/3.10/library/ssl.html#ssl.SSLContext.minimum_version
         # https://docs.python.org/3.7/library/ssl.html#ssl.SSLContext.minimum_version
         context.minimum_version = ssl.TLSVersion.TLSv1_2
     else:
         # If 'minimum_version' isn't available, we configure these options with
         # the older deprecated variants.
         context.options |= ssl.OP_NO_SSLv2
         context.options |= ssl.OP_NO_SSLv3
         context.options |= ssl.OP_NO_TLSv1
         context.options |= ssl.OP_NO_TLSv1_1
```

2021-06-25 10:21 UTC, graingert commented on httpx/_compat.py
> +    # with OpenSSL 1.1.0g or newer.
```suggestion
    # with OpenSSL 1.1.0g or newer.
    # https://docs.python.org/3.10/library/ssl.html#ssl.SSLContext.minimum_version
    # https://docs.python.org/3.7/library/ssl.html#ssl.SSLContext.minimum_version
```

2021-06-25 10:29 UTC, tomchristie requested changes

2021-06-25 10:29 UTC, tomchristie commented on httpx/_compat.py
> +if sys.version_info >= (3, 10) or (
So there's still a little too much unnecessary change footprint here. We don't really need to switch the structure around here. Let's keep `set_minimum_tls_version_1_2` as the top level function, with the switch *inside* it.

We really just want to:

* Update the `sys.version_info >= (3, 10)` branch condition.
* Possibly neaten up the commenting.

2021-06-25 10:40 UTC, graingert commented on httpx/_compat.py
>          context.options |= ssl.OP_NO_SSLv2
```suggestion
        # If 'minimum_version' isn't available, we configure these options with
        # the older deprecated variants.
        context.options |= ssl.OP_NO_SSLv2
```

2021-06-28 12:08 UTC, tomchristie approved these changes

2021-06-28 12:12 UTC, tomchristie commented
Fab! ✨

2021-06-28 12:12 UTC, merged