[WIP]: make `raise_for_status` chainable
encode/httpx pull request #2776
Opened 2023-07-15 08:29 UTC by trim21

# Summary
make it possible to write code like `r = httpx.get('...').raise_for_status().json()`

https://github.com/encode/httpx/discussions/2775

# Checklist

- [X] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [X] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.

2023-07-31 12:04 UTC, abersheeran approved these changes
LGTM. It's a small change, but the experience will be much better.

2023-07-31 12:28 UTC, tomchristie commented
Okay great, so...

* CHANGELOG.
* Do we want to mention this usage style in the docstring? In the docs?

2023-07-31 15:33 UTC, zanieb commented
I think this usage should be mentioned in the docstring and docs

2023-07-31 16:04 UTC, michaeloliverx commented
Really nice DX improvement here, I see myself using this a lot!

2023-07-31 19:40 UTC, trim21 commented
document updated

2023-08-01 09:03 UTC, tomchristie commented on CHANGELOG.md
> +* Make `Reaponse.raise_for_status()` chainable, now it's possible to validate response and get json data in one line: `data = httpx.get('...').raise_for_status().json()`. (#2776)
```suggestion
* The `Response.raise_for_status()` method now returns the response instance. For example: `data = httpx.get('...').raise_for_status().json()`. (#2776)
```

2023-08-01 09:03 UTC, tomchristie commented on docs/quickstart.md
> +Any successful response codes will simply return `Resposne` itself rather than raising an exception.
```suggestion
Any successful response codes will simply return `Response` itself rather than raising an exception.
```

2023-08-01 09:07 UTC, tomchristie requested changes
Looks good. Some minor suggestions...

(Other could also be considered)

2023-08-01 09:07 UTC, tomchristie commented on docs/quickstart.md
> +Any successful response codes will simply return `Resposne` itself rather than raising an exception.
```suggestion
Any successful response codes will return the `Response` instance rather than raising an exception.
```

2023-08-01 09:07 UTC, tomchristie commented on CHANGELOG.md
> +* Make `Reaponse.raise_for_status()` chainable, now it's possible to validate response and get json data in one line: `data = httpx.get('...').raise_for_status().json()`. (#2776)
```suggestion
* The `Response.raise_for_status()` method now returns the response instance. For example: `data = httpx.get('...').raise_for_status().json()`. (#2776)
```

2023-08-01 09:07 UTC, tomchristie commented on docs/quickstart.md
> +You can just call it after HTTP method to verify response code.
```suggestion
The method returns the response instance, allowing you to use it inline. For example:
```

2023-08-01 09:22 UTC, tomchristie approved these changes

2023-08-01 09:22 UTC, merged

2023-08-01 10:01 UTC, trim21 commented
is there any ETA on next release?

2023-08-01 10:10 UTC, tomchristie commented
If you're up for helping drive a release pull request, then we could fix up a minor point release whenever really.

2023-08-01 10:27 UTC, karosis88 commented
> If you're up for helping drive a release pull request, then we could fix up a minor point release whenever really.

Can we include https://github.com/encode/httpcore/pull/745 in the next httpx release?

First, we should release httpcore with that pull request and then release httpx