Raise ValueError on change encoding
encode/httpx pull request #2852
Opened 2023-09-17 00:53 UTC by xzmeng

Discussed in #2041

# Summary

After `Response.text` is accessed, if you try to change `Response.encoding`, nothing happens. So just raise an Exception on change to `encoding` after `text` is accessed.

# Checklist

- [x] I understand that this PR may be closed in case there was no previous discussion. (This doesn't apply to typos!)
- [x] I've added a test for each change that was introduced, and I tried as much as possible to make a single atomic change.
- [ ] I've updated the documentation accordingly.

2023-09-17 08:50 UTC, tomchristie commented
Okay yes, as discussed this is probably a marginal improvement in behaviour. Thanks.

2023-09-17 08:52 UTC, tomchristie requested changes

2023-09-17 08:52 UTC, tomchristie commented on tests/models/test_responses.py
> +    response.encoding = "UTF8"
I'd expect the `ValueError` to be raised here. I don't think we need the conditional "don't raise if the encoding is being set but the resulting codec won't change".

Simplicity over complexity where possible.

2023-09-18 09:40 UTC, tomchristie commented
What's a more precise title for this PR?

2023-09-18 09:53 UTC, xzmeng commented
Modified. I'm not proficient in English, please change it if it's not appropriate.

2023-09-18 10:32 UTC, karosis88 approved these changes

2023-09-18 10:41 UTC, tomchristie reviewed
All looking great, thanks. 😊

I think we just need to update the `CHANGELOG.md`, then this is good to go.

2023-09-19 07:54 UTC, tomchristie approved these changes

2023-09-19 07:54 UTC, merged