Add the 'proxy' parameter and deprecate 'proxies'.
encode/httpx pull request #2879
Opened 2023-10-06 13:24 UTC by karpetrosyan

# Summary

This pull request simply deprecates the `proxies` argument and instead adds a `proxy` argument.
Httpx supports `proxies` and `mounts` arguments, which are not the same, but mounts can simply replace proxies for complex routing, which is not always used.

So for simplicity, this PR deprecates `proxies` and adds `proxy` argument.

Now the user should use...

- `proxy` if you want to use a proxy server for all your requests.
- `mounts` if you want to use a proxy server for requests matching the URL pattern you specified.

## Proxy

```python
import httpx

# instead of 
# httpx.Client(proxies="http://127.0.0.1:80")
# and
# httpx.Client(proxies={"all://": "http://127.0.0.1:80"})
# do ...
client = httpx.Client(proxy="http://127.0.0.1:80")
```

## Mounts

```python
import httpx

# instead of
# client = httpx.Client(
#    proxies={"http://": "http://127.0.0.1:80", "https://": "https://127.0.0.1:443"}
# )
# do ...
client = httpx.Client(
    mounts={
        "http://": httpx.HTTPTransport(proxy=httpx.Proxy("http://127.0.0.1:80")),
        "https://": httpx.HTTPTransport(proxy=httpx.Proxy("https://127.0.0.1:443")),
    }
)
```

2023-10-07 06:39 UTC, karpetrosyan commented
@encode/maintainers If we want to switch to this API, I can work on the documentation.

I don't want to rush API changes, but if we **believe the `proxies` API is not persistent**, we should probably change it before 1.0.0, for example, deprecate it in the next release and remove it in 1.0.0.

2023-10-10 13:11 UTC, tomchristie commented
Yep seems like a clear API rationalisation to me, I'd be happy for us to make this switch for 1.0.

It woud probably also make sense for us to widen the available types for the `proxy` argument on `httpx.HTTPTransport`, so that the mount style is kept fairly simple...

```python
client = httpx.Client(
    mounts={
        "http://": httpx.HTTPTransport(proxy="http://127.0.0.1:80"),
        "https://": httpx.HTTPTransport(proxy="https://127.0.0.1:443"),
    }
)
```

2023-10-11 04:17 UTC, T-256 approved these changes

2023-10-11 04:17 UTC, T-256 commented on httpx/_transports/default.py
> +from httpx import URL
```suggestion
```

2023-10-11 04:17 UTC, T-256 commented on httpx/_transports/default.py
> +from .._types import AsyncByteStream, CertTypes, ProxyTypes, SyncByteStream, VerifyTypes
```suggestion
from .._types import AsyncByteStream, CertTypes, ProxyTypes, SyncByteStream, VerifyTypes
from .._urls import URL
```

2023-10-11 09:06 UTC, karpetrosyan commented
Okay, so I can say that we should carefully consider how we will document this.
At this time, all of the routing staff described in the `HTTP Proxies` section do not make sense with the current implementation. 
I propose that we change the documentation in a separate PR, and that we also document this feature there.

That new PR should answer this question:

- What structure do we want for the HTTPX 1.0 documentation?
- How do we want to document the deprecated things?
- Do we want to describe custom transports more detailed? & Move the routing section into it.

2023-10-11 10:25 UTC, tomchristie commented
Excellent questions, though quite wide ranging.

For the purposes *of this pull request* I'd suggest that...

* The proxy routing docs move into the "mounting transports" section.
* Deprecations are mentioned in the `CHANGELOG`.

2023-10-11 11:21 UTC, karpetrosyan commented
> Excellent questions, though quite wide ranging.
> 
> For the purposes _of this pull request_ I'd suggest that...
> 
> * The proxy routing docs move into the "mounting transports" section.
> * Deprecations are mentioned in the `CHANGELOG`.

Do you agree that we should do all the documentation for HTTPX 1.0 in a separate pull request?

2023-10-12 08:03 UTC, karpetrosyan commented on httpx/_types.py
> +ProxiesTypes = Union[URLTypes, ProxyTypes, Dict[URLTypes, Union[None, ProxyTypes]]]
```suggestion
ProxiesTypes = Union[ProxyTypes, Dict[URLTypes, Union[None, ProxyTypes]]]
```

2023-10-12 08:34 UTC, tomchristie requested changes
Looking good.

The command-line client also currently uses `--proxies` - I'd suggest we change that also.

For example here...

https://github.com/encode/httpx/blob/e63b6594f2863b7c8274eb0991ebc6cad63661f7/httpx/_main.py#L72

as well as in a few other places in that module.

2023-10-12 09:07 UTC, karpetrosyan commented
Do we want to keep the proxies argument in the cli app?
The migration is so easy; **the user should just change the `proxies` word to `proxy`**, so we can entirely remove it.

2023-10-13 12:29 UTC, tomchristie commented
> the user should just change the proxies word to proxy

I'm happy with making that change, yes.

2023-11-17 13:27 UTC, tomchristie commented
Seems like a nice change to me, helps simplify things a bit.

Once we've merged this one we're prob committing ourselves to a major version we okay with that?

2023-11-17 14:05 UTC, karpetrosyan commented
> Once we've merged this one we're prob committing ourselves to a major version we okay with that?

Let's put this in the next minor version for now, and then we'll completely switch to the new API with HTTPX 1.0 :tada:

2023-12-11 12:08 UTC, tomchristie commented on CHANGELOG.md
> +* The `proxies` argument is now deprecated and supposed to be replaced by the `proxy` argument. (#2879)
```suggestion
* The `proxies` argument is now deprecated. You should use the `proxy` argument instead, or use `mounts=` for more complex configurations. (#2879)
```

2023-12-11 12:09 UTC, tomchristie commented on docs/troubleshooting.md
>  }
I'd suggest we use the variable name `mounts` here...

```suggestion
mounts = {
  "http://": httpx.HTTPTransport(proxy="http://myproxy.org"),
  "https://": httpx.HTTPTransport(proxy="https://myproxy.org"),
}
```

2023-12-11 12:09 UTC, tomchristie commented on docs/troubleshooting.md
> +  "https://": httpx.HTTPTransport(proxy="http://myproxy.org"),
```suggestion
mounts = {
  "http://": httpx.HTTPTransport(proxy="http://myproxy.org"),
  "https://": httpx.HTTPTransport(proxy="http://myproxy.org"),
```

2023-12-11 12:16 UTC, tomchristie commented
Looking great. Let's...

* Update the description to indicate that `proxies=...` *will* continue to work at this point in time, but will issue a warning. (That's correct yeah?)
* Should we drop `proxies` from the docstrings at this point, given that it's deprecated. Perhaps code comments alongside `proxies=...` indicating "# Deprecated. Remains functional, but will raise a warning if used."`?

2023-12-11 13:50 UTC, tomchristie approved these changes

2023-12-11 13:55 UTC, merged