Clarified error when header value is None
encode/httpx pull request #3312
Opened 2024-09-23 18:12 UTC by nomilkinmyhome

Previously, when the header value was None, a misleading error was thrown: "AttributeError: Object 'NoneType' does not have attribute 'encode'." Now it looks better.

![image](https://github.com/user-attachments/assets/ec12330f-aa7e-4084-8c81-c89aef8fdea9)

2024-09-25 20:59 UTC, zanieb commented on .gitignore
> +.idea
This probably belongs in your user-level `.gitignore` — there are no editor-specific ignore entries here.

2024-09-25 21:01 UTC, zanieb approved these changes
Thanks this seems reasonable to me, the error message is much more friendly. I want to make sure another maintainer signs-off that we want to have these kinds of checks in general though.

2024-09-25 21:01 UTC, zanieb commented on .gitignore
> +.idea
```suggestion
```

2024-09-26 14:35 UTC, tomchristie requested changes
Brilliant, thanks. I've requested a change to the tests, let me know if needs any more explanation.

(We should always be testing against public API. There's a couple of places left to clean up, tho we're almost there now)

2024-09-26 14:35 UTC, tomchristie commented on tests/test_utils.py
> +        normalize_header_value(None)  # type: ignore
Could we have these tests in `tests/client/test_headers.py` with the testing against `httpx.Header(...)` instead of against the internal API?

2024-09-26 17:01 UTC, tomchristie approved these changes
👌

2024-09-26 17:01 UTC, merged